- name: Install epel repo for RHEL/Centos
  yum:
    name: epel-release
    state: latest
    enablerepo: base
    
- name: install the latest version of jq (JSON processor) and curl - RedHat
  yum:
    name: jq
    state: latest
